alias cls='printf "\033c"'
alias aptclean='sudo apt autoremove --purge'
alias osver='cat /etc/os-release'
alias piver='cat /proc/device-tree/model;printf "\n"'
alias pitemp='vcgencmd measure_temp | egrep -o "[0-9]*\.[0-9]*.{2}"'
alias listsvc='systemctl list-unit-files --type=service'
alias listenable='systemctl list-unit-files --type=service --state=enabled'
alias liteon='sudo bash -c "echo 0 > /sys/class/backlight/rpi_backlight/bl_power"'
alias liteoff='sudo bash -c "echo 1 > /sys/class/backlight/rpi_backlight/bl_power"'
alias hdmion='sudo /opt/vc/bin/tvservice -p'
alias hdmioff='sudo /opt/vc/bin/tvservice -o'
alias screenoff='sudo vcgencmd display_power 0'
alias screenon='sudo vcgencmd display_power 1'
alias jimmies='echo 1 | sudo tee /proc/sys/kernel/sysrq;echo s | sudo tee /proc/sysrq-trigger;echo u | sudo tee /proc/sysrq-trigger;echo b | sudo tee /proc/sysrq-trigger'
